"use client";
import "@/assets/style/main.css";
import "@/assets/style/style.css";
import "@/assets/style/util.css";
import HeaderComponents from "@/components/header";
import {
  AppBar,
  Box,
  CssBaseline,
  Toolbar,
  Typography
} from "@mui/material";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <HeaderComponents /> */}
        {/* <Providers>{children}</Providers> */}
        {/* <FooterComponent /> */}

        <Box sx={{ display: "flex" }}>
          <CssBaseline />
          <AppBar
            position="fixed"
            sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}
          >
            <Toolbar>
              <Typography variant="h6" noWrap component="div">
                Shop bán hàng
              </Typography>
            </Toolbar>
          </AppBar>
          <HeaderComponents />
          <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
            <Toolbar />
            <Providers>{children}</Providers>
          </Box>
        </Box>
      </body>
    </html>
  );
}
